# -*- coding: utf-8 -*-
"""
Created on Mon Oct  5 10:27:43 2020

@author: Web
"""

category_map = {\
        'Disc Golf/Bag':'Misc',
        'Electronic/Audio':'Misc',
        'Electronic/Camera/Accessory':'Misc',
        'Eyewear/Goggles/Accessory':'Outerwear/Goggles/Accessory',
        'Eyewear/Goggles/Moto':'Outerwear/Goggles/Accessory',
        'Eyewear/Goggles/Rep. Lens':'Outerwear/Goggles/Accessory',
        'Eyewear/Goggles/Unisex':'Outerwear/Goggles/Adult',
        'Eyewear/Goggles/Womens':'Outerwear/Goggles/Women',
        'Eyewear/Goggles/Youth':'Outerwear/Goggles/Youth',
        'Eyewear/Sunglasses/Accessory':'Lifestyle/Sunglasses/Accessory',
        'Eyewear/Sunglasses/Unisex':'Lifestyle/Sunglasses/Unisex',
        'Eyewear/Sunglasses/Womens':'Lifestyle/Sunglasses/Womens',
        'Headwear/Beanie':'Outerwear/Headwear/Beanie',
        'Headwear/Facemask':'Outerwear/Headwear/Facemask',
        'Headwear/Hat':'Lifestyle/Accessory',
        'Hike/Pack/Accessory':'Lifestyle/Accessory',
        'Hike/Pack/Hydration':'Lifestyle/Accessory',
        'Hike/Pack/Map/Book':'Lifestyle/Accessory',
        'Hike/Pack/Mens/Shoes':'Lifestyle/Men/Shoes',
        'Hike/Pack/Womens/Shoes':'Lifestyle/Women/Shoes',
        'Kayak/Accessory':'Watersport/Kayak',
        'Lifejacket/Neoprene/Dog':'Watersport/Life Jackets/Dog',
        'Lifejacket/Neoprene/Men':'Watersport/Life Jackets/Men',
        'Lifejacket/Neoprene/Womens':'Watersport/Life Jackets/Women',
        'Lifejacket/Neoprene/Youth':'Watersport/Life Jackets/Youth',
        'Lifejacket/Nylon/Men':'Watersport/Life Jackets/Men',
        'Lifejacket/Nylon/Womens':'Watersport/Life Jackets/Women',
        'Lifejacket/Nylon/Youth':'Watersport/Life Jackets/Youth',
        'Mens/Baselayer/Bottom':'Outerwear/Base Layer/Men',
        'Mens/Baselayer/Suit':'Outerwear/Base Layer/Men',
        'Mens/Baselayer/Top':'Outerwear/Base Layer/Men',
        'Mens/Lifestyle/Accessory':'Lifestyle/Men/Accessory',
        'Mens/Lifestyle/Bag':'Lifestyle/Men/Accessory',
        'Mens/Lifestyle/Jacket':'Lifestyle/Men/Jacket',
        'Mens/Lifestyle/Pants':'Lifestyle/Men/Pants',
        'Mens/Lifestyle/Shoes':'Lifestyle/Men/Shoes',
        'Mens/Lifestyle/Shorts':'Lifestyle/Men/Shorts',
        'Mens/Lifestyle/Top':'Lifestyle/Men/Tops',
        'Mens/Midlayer':'Outerwear/Midlayer/Men',
        'Mens/Outerwear/Gloves':'Outerwear/Gloves/Men',
        'Mens/Outerwear/Jackets':'Outerwear/Jacket/Men',
        'Mens/Outerwear/Mittens':'Outerwear/Gloves/Women',
        'Mens/Outerwear/Pants':'Outerwear/Pants/Men',
        'Mens/Outerwear/Suit':'Outerwear/Suit',
        'Mens/Swimwear/Shorts':'Lifestyle/Men/Shorts',
        'Race/Night':'Misc',
        'Safety/Avalanche/Probe':'Misc',
        'Safety/Avalanche/Shovel':'Misc',
        'Safety/Avalanche/Tranceiver':'Misc',
        'Safety/Helmet/Skate':'Skate/Helmets',
        'Safety/Helmet/Ski':'Ski/Helmets',
        'Safety/Helmet/Wakeboard':'Watersport/Wakeboard/Accessory',
        'Safety/Pad/Skate':'Skate/Accessory',
        'Safety/Pad/Snow':'Snowboard/Accessory',
        'Safety/Race/Ski':'Ski/Accessory',
        'Skateboard/Accessory':'Skate/Accessory',
        'Skateboard/Bearings':'Skate/Bearings',
        'Skateboard/Complete/Street':'Skate/Completes',
        'Skateboard/Completes/Long Board':'Skate/Completes',
        'Skateboard/Deck/Street':'Skate/Decks',
        'Skateboard/Griptape':'Skate/Accessory',
        'Skateboard/Hardware':'Skate/Accessory',
        'Skateboard/Shoes/Mens':'Skate/Shoes/Men',
        'Skateboard/Shoes/Womens':'Skate/Shoes/Women',
        'Skateboard/Trucks/Street':'Skate/Trucks',
        'Skateboard/Wheels/Longboard':'Skate/Wheels',
        'Skateboard/Wheels/Street':'Skate/Wheels',
        'Ski/Accessory':'Ski/Accessory',
        'Ski/Accessory/Insoles':'Ski/Accessory',
        'Ski/Bags/Backpack':'Ski/Accessory',
        'Ski/Bags/Boot':'Ski/Accessory',
        'Ski/Bags/Outerwear/':'Ski/Accessory',
        'Ski/Bags/Ski':'Ski/Accessory',
        'Ski/Bindings/Mens':'Ski/Bindings/Men',
        'Ski/Bindings/Womens':'Ski/Bindings/Women',
        'Ski/Bindings/Youth':'Ski/Bindings/Youth',
        'Ski/Boots/Accessory':'Ski/Accessory',
        'Ski/Boots/Liner':'Ski/Accessory',
        'Ski/Boots/Mens':'Ski/Boots/Men',
        'Ski/Boots/Parts':'Ski/Boots/Parts',
        'Ski/Boots/Womens':'Ski/Boots/Women',
        'Ski/Boots/Youth':'Ski/Boots/Youth',
        'Ski/Poles/Accessory':'Ski/Accessory',
        'Ski/Poles/Adult':'Ski/Poles/Adult',
        'Ski/Poles/Baskets':'Ski/Accessory',
        'Ski/Poles/Youth':'Ski/Poles/Youth',
        'Ski/Skis/Mens':'Ski/Skis/Men',
        'Ski/Skis/Womens':'Ski/Skis/Women',
        'Ski/Skis/Youth':'Ski/Skis/Youth',
        'Ski/Socks/Adult':'Ski/Socks/Adult',
        'Ski/Socks/Youth':'Ski/Socks/Youth',
        'Ski/Tune/Wax':'Ski/Accessory',
        'Ski/Tuning/Tool':'Ski/Accessory',
        'Ski/X-Country/Bindings':'Ski/Accessory',
        'Ski/X-Country/Boots':'Ski/Accessory',
        'Ski/X-Country/Skis':'Ski/Accessory',
        'Snowboard/Accessory':'Snowboard/Accessory',
        'Snowboard/Bags/Backpack':'Snowboard/Bags/Backpack',
        'Snowboard/Bags/Board Bag':'Snowboard/Bags/Board',
        'Snowboard/Bags/Outerwear/':'Snowboard/Bags/Outerwear/',
        'Snowboard/Bags/Travel':'Snowboard/Bags/Travel',
        'Snowboard/Bags/Wheel':'Snowboard/Bags/Wheel',
        'Snowboard/Bindings/Unisex':'Snowboard/Bindings/Adult',
        'Snowboard/Bindings/Women':'Snowboard/Bindings/Women',
        'Snowboard/Bindings/Youth':'Snowboard/Bindings/Youth',
        'Snowboard/Board/Mens':'Snowboard/Board/Men',
        'Snowboard/Board/Womens':'Snowboard/Board/Women',
        'Snowboard/Board/Youth':'Snowboard/Board/Youth',
        'Snowboard/Boots/Mens':'Snowboard/Boots/Men',
        'Snowboard/Boots/Womens':'Snowboard/Boots/Women',
        'Snowboard/Boots/Youth':'Snowboard/Boots/Youth',
        'Snowboard/Socks/Adult':'Snowboard/Accessory',
        'Snowboard/Socks/Youth':'Snowboard/Accessory',
        'Stupid/Misc/Crap':'Misc',
        'Wakeboard/Accessory':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Bags':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Board/Mens':'Watersport/Wakeboard/Board',
        'Wakeboard/Boots/Unisex':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Boots/Womens':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Packages/Unisex':'Watersport/Wakeboard/Package Deals',
        'Wakeboard/Packages/Womens':'Watersport/Wakeboard/Package Deals',
        'Wakeboard/Packages/Youth':'Watersport/Wakeboard/Package Deals',
        'Wakeboard/Surf/Accessory':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Surf/Bag':'Watersport/Wakeboard/Accessory',
        'Wakeboard/Wakeskate':'Watersport/Wakesurf',
        'Wakeboard/Wakesurfs':'Watersport/Wakesurf',
        'Watersport/Kneeboard/Board':'Watersport/Kneeboard',
        'Watersport/Rashguard/Mens':'Watersport/Outfit/Rashguard',
        'Watersport/Rashguard/Womens':'Watersport/Outfit/Rashguard',
        'Watersport/Ski/Accessory':'Watersport/Water Ski/Accessory',
        'Watersport/Ski/Bag':'Watersport/Water Ski/Accessory',
        'Watersport/Ski/Bindings':'Watersport/Water Ski/Accessory',
        'Watersport/Ski/Combo':'Watersport/Water Ski/Combo',
        'Watersport/Ski/Handle':'Watersport/Water Ski/Handle',
        'Watersport/Ski/Single':'Watersport/Water Ski/Single',
        'Watersport/Towable/Accessory':'Watersport/Towable/Accessory',
        'Watersport/Towable/Tube':'Watersport/Towable/Tube',
        'Watersport/Wetsuit/Mens':'Watersport/Outfit/Wetsuit',
        'Watersport/Wetsuit/Womens':'Watersport/Outfit/Wetsuit',
        'Watersport/Wetsuit/Youth':'Watersport/Outfit/Wetsuit',
        'Winter/Equipment':'Misc',
        'Women/Outerwear/Suit':'Outerwear/Suit',
        'Womens/Baselayer/Bottom':'Outerwear/Base Layer/Women',
        'Womens/Baselayer/Suit':'Outerwear/Base Layer/Women',
        'Womens/Baselayer/Top':'Outerwear/Base Layer/Women',
        'Womens/Lifestyle/Accessory':'Lifestyle/Women/Accessory',
        'Womens/Lifestyle/Dress':'Lifestyle/Women/Dress',
        'Womens/Lifestyle/Jacket':'Lifestyle/Women/Jacket',
        'Womens/Lifestyle/Jumpsuit':'Lifestyle/Women',
        'Womens/Lifestyle/Pants':'Lifestyle/Women/Pants',
        'Womens/Lifestyle/Shoes':'Lifestyle/Women/Shoes',
        'Womens/Lifestyle/Shorts':'Lifestyle/Women/Shorts',
        'Womens/Lifestyle/Top':'Lifestyle/Women/Tops',
        'Womens/Midlayer':'Outerwear/Midlayer/Women',
        'Womens/Outerwear/Gloves':'Outerwear/Gloves/Women',
        'Womens/Outerwear/Jacket':'Outerwear/Jacket/Women',
        'Womens/Outerwear/Mittens':'Outerwear/Mittens/Women',
        'Womens/Outerwear/Pants':'Outerwear/Pants/Women',
        'Womens/Swimwear':'Lifestyle/Women/Swimwear',
        'Youth/Baselayer/Bottom':'Outerwear/Base Layer/Youth',
        'Youth/Baselayer/Suit':'Outerwear/Base Layer/Youth',
        'Youth/Baselayer/Top':'Outerwear/Base Layer/Youth',
        'Youth/Outerwear/Gloves':'Outerwear/Gloves/Youth',
        'Youth/Outerwear/Jacket':'Outerwear/Jacket/Youth',
        'Youth/Outerwear/Mittens':'Outerwear/Mittens/Youth',
        'Youth/Outerwear/Pants':'Outerwear/Pants/Youth',
        'Clearance/Climbing':'Clearance/Climbing',
        'Clearance/Headwear':'Clearance/Headwear',
        'Clearance/Water Sports':'Clearance/Water Sports',
        'Clearance/Outerwear':'Clearance/Outerwear',
        'Clearance/Headwear':'Clearance/Headwear',
        'Clearance/Ski':'Clearance/Ski',
        'Clearance/Ski/Bindings':'Clearance/Ski/Bindings',
        'Clearance/Ski/Boots':'Clearance/Ski/Boots',
        'Clearance/Ski':'Clearance/Ski',
        'Clearance/Ski/Youth':'Clearance/Ski/Youth',
        'Clearance/Snowboard':'Clearance/Snowboard',
        'Clearance/Snowboard/Boots':'Clearance/Snowboard/Boots',
        'Clearance/Snowboard':'Clearance/Snowboard',
        'Clearance/Snowboard/Youth':'Clearance/Snowbaord/Youth',
        'Clearance/Snowshoe':'Clearance/Snowshoe',
        'Clearance/Snowshoe/Youth':'Clearance/Snowshoe/Youth',
        'Clearance/SUP':'Clearance/SUP',
        'Clearance/Water Sports':'Clearance/Water Sports',
        'Clearance/X-Country':'Clearance/X-Country'}

clearance_map = {'CLBAXE':'Clearance/Climbing',
                'CLBBOO':'Clearance/Climbing',
                'CLBCRA':'Clearance/Climbing',
                'CLBHEL':'Clearance/Climbing',
                'CLBPRT':'Clearance/Climbing',
                'EYEGOG':'Clearance/Headwear',
                'HEL':'Clearance/Headwear',
                'KAYADU':'Clearance/Water Sports',
                'LIFADU':'Clearance/Water Sports',
                'OUTJKT':'Clearance/Outerwear',
                'OUTPNT':'Clearance/Outerwear',
                'SAFHEL':'Clearance/Headwear',
                'SKI':'Clearance/Ski',
                'SKIADU':'Clearance/Ski',
                'SKIBIN':'Clearance/Ski/Bindings',
                'SKIBND':'Clearance/Ski/Bindings',
                'SKIBOO':'Clearance/Ski/Boots',
                'SKIDEM':'Clearance/Ski',
                'SKIPOL':'Clearance/Ski',
                'SKISKI':'Clearance/Ski',
                'SKIYOU':'Clearance/Ski/Youth',
                'SNBADU':'Clearance/Snowboard',
                'SNBBND':'Clearance/Snowboard',
                'SNBBOO':'Clearance/Snowboard/Boots',
                'SNBBRD':'Clearance/Snowboard',
                'SNBDEM':'Clearance/Snowboard',
                'SNBYOU':'Clearance/Snowbaord/Youth',
                'SNO':'Clearance/Snowshoe',
                'SNOBOO':'Clearance/Snowshoe',
                'SNOYOU':'Clearance/Snowshoe/Youth',
                'SUPADU':'Clearance/SUP',
                'WAKBRD':'Clearance/Water Sports',
                'WAKDEM':'Clearance/Water Sports',
                'WAKWSF':'Clearance/Water Sports',
                'WATSKI':'Clearance/Water Sports',
                'WATWAK':'Clearance/Water Sports',
                'XCSBOO':'Clearance/X-Country',
                'XCSPOL':'Clearance/X-Country',
                'XCSSKI':'Clearance/X-Country'}