amazon_excluded_vendors = [
    "686",
    "Arbor Snowboards",
    "Arcade Belts",
    "Bronson Speed Co.",
    "Bullet",
    "Burton",
    "Capita",
    "Crab Grab",
    "Creature",
    "Darn Tough",
    "Fox",
    "Giro",
    "Gnu",
    "Havaianas",
    "Helly Hansen",
    "Hestra",
    "Hot Chillys",
    "Hydro Flask",
    "Independent",
    "Lib Technologies",
    "Marmot",
    "Nike",
    "Nikwax",
    "OJ Iii",
    "PIT VIPER",
    "Picture Organic Clothing",
    "RVCA",
    "Reef",
    "Ricta",
    "Salomon Ski",
    "Santa Cruz",
    "Smartwool",
    "Smith",
    "Spyder Active Sports",
    "Stance",
    "Sun Bum",
    "The North Face",
    "Theragun",
    "Turtle Fur",
    "Under Armour",
    "Union Binding Company",
    "Vans",
    "Wolfgang",
]
